### ISSUE TITLE
Generic configurations/step definitions

### ISSUE THREAD

**Issue by faultyserver** [faultyserver/wrkflo#3]
It'd be nice to be able to have more generic steps to allow for more powerful configurations.

For example, there are currently (`v0.0.5`) two step definitions for text editors - `emacs` and `sublime`. If I (a Sublime user) share a configuration with someone who uses Emacs, they have to change every entry of `sublime` in their configuration to use `emacs`.

A nicer approach would be adding a generic `editor` step that can launch the user's preferred editor. This would require two things:

  - The concept of "abstract steps" that define a configuration schema and some high-level functionality. Concrete sub-steps can then implement the low-level, app-specific functionality using that configuration.
  - An `options` section in `~/.wrkflorc` to choose between concrete implementations of the abstract steps.

The example configuration from this repo could then look like this:

```yaml
options:
  # Choose an editor that all steps will use by default
  editor: sublime

work_remote:
  sshfs:
    host: myserver.example.com
    remote_path: ~/sites/my_site
    local_path: ~/remote
  ssh:
    host: myserver.example.com
    command: cd ~/sites/my_site
  # Having only a `path` configuration implies that `sublime` will be the editor
  editor:
    path: ~/remote

with_override:
  sshfs:
    host: myserver.example.com
    remote_path: ~/sites/my_site
    local_path: ~/remote
  ssh:
    host: myserver.example.com
    command: cd ~/sites/my_site
  # Overriding the default option would also be a nice feature
  editor:
    which: sublime
    path: ~/remote

```
