### ISSUE TITLE
Dynamic step loading

### ISSUE THREAD

**Issue by faultyserver** [faultyserver/wrkflo#6]
Currently, all steps are defined in `lib/wrkflo/steps/`, and they are loaded immediately after `Step` is loaded.

To allow users to load custom steps without having to PR the repo/edit the gem, there should be some way of loading steps from another directory (maybe `~/.wrkflo/steps/` by default?) and/or allowing users to specify step definitions in `~/.wrkflorc`.

**Comment by faultyserver** [comment]
I'm thinking about how to represent this information in `~/.wrkflorc`. My best solution for now is to allow for an array under `options` like so:

```yaml
options:
  editor: sublime
  filesystem: sshfs
  step_definitions:
    # Paths mapping to directories will be scanned for `.rb` files.
    - ~/.wrkflo/my_steps
    - ~/Sites/some_site/.wrkflo
    # Paths to a single file will be included directly.
    - ~/path/to/some_step.rb
    # Gems can also be included directly.
    - wrkflo-vim
```

Another good thing to add would be including more paths to check by default such as `~/.wrkflo/steps/*`, and `./.wrkflo/steps/*`.
